### ISSUE TITLE
[BUG]- Modernization Scanner: throws "Value cannot be null" error when I click on Scan now

### ISSUE THREAD

**Issue by Arun-Chandra** [pnp/sp-dev-modernization#530] opened 2020-09-14 11:45 UTC
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior
Uanlbe to configure SharePoint modernization scanner, when I click Start scan it results with Error
_
#### Observed Behavior
The Modernization scanner is located here - https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner. I want to configure this Modernization Scanner to my tenant using username and password.1.	I have multiple task to be achieved using the Scanner application example Workflows, classic sites and so on

I tried on multiple machines , different user ID’s same result

#### Steps to Reproduce
Modernization Scanner to my tenant using username and password. 
	I have multiple task to be achieved using the Scanner application example Workflows, classic sites and so on	

#### Submission Guidelines

_

**Comment by Arun-Chandra** [comment] 2020-09-14 11:47
Cant attach a file to this BUG

**Comment by Arun-Chandra** [comment] 2020-09-14 11:49
Error text:

Launching Wizard...

Scanning is starting... 8/31/2020 8:26:09 AM


For Error pic - refer to issue #524
Error executing scan:
 Value cannot be null.
 Parameter name: value
 Press any key to continue

After I press any key , the application dissappears

**Comment by jansenbe** [comment] 2020-09-14 13:13
Duplicate of #524, please check that thread. I'm closing this issue now

**Closed by jansenbe** 2020-09-14 13:13 UTC
