### ISSUE TITLE
Modernization Scanner did not show the Document Content Type workflows in report

### ISSUE THREAD

**Issue by ooiming** [pnp/sp-dev-modernization#562] opened 2020-12-22 14:54 UTC
Previous issue reported in #537 is still not yet resolved with 2.18. 
The same document content type workflow reported in #537 is still not shown in the report generated using v2.18  --> Document Content Type workflow called "Special Quote" in a document library (called "Cases"). We are able to see this workflow using SharePoint Designer.
- There is no workflow associate to this "Cases" library, but there are couple of workflows associate to documents in this library (all workflows associate at document in this library are not shown in the report).
- This library is located in a subsite.

![SpecialQuotes_CasesLibrary](https://user-images.githubusercontent.com/72455168/102901342-7d3f6d00-443b-11eb-8725-588c1ee336fc.png)
![SpecialQuotesApproval](https://user-images.githubusercontent.com/72455168/102901361-84667b00-443b-11eb-90c6-7ef87e65502c.png)
![SpecialQuotesApproval(ViewFromSPD)](https://user-images.githubusercontent.com/72455168/102901367-87fa0200-443b-11eb-8e8b-bf6aed742583.png)

**Comment by jansenbe** [comment] 2021-02-03 15:36
Hi @ooiming ,

I've been testing various WF scenarios with the latest scanner but for now I'm not able to reproduce. See below for the used test scenario. Do you have repro steps that result in a used WF which is not reported by the scanner?

1/ Inherited custom content type

Add new site CT (=WFDocument) inheriting from document CT
Add new site CT (=WFDocumentChild) inheriting from WFDocument
Created a sub site structure of 3 levels
Added a document library on a level 3 sub site
Added the WFDcoument content type to a document library at level 2
Added the WFDocumentChild content type to the document library at level 3
Updated the WFDocument in the root site by adding an OOB 2010 approval WF to it
Scanner output:

lists the WFDocumentChild content type in the level 3 sub site linked to the list: OK
lists the WFDocument content type in the level 2 sub site linked to the list: OK
list the WFDocument and WFDocumentChild content types in the root site without linking info: OK
2/ Use SPD to create a custom content type at sub site level

Add new CT (=WfDocumentChildAtWebLevel) via SPD in the level 3 sub site
Add new level 4 sub site
Connect WfDocumentChildAtWebLevel to new doc lib at level 4 sub site
Scanner output:

Lists the WfDocumentChildAtWebLevel content type at level 3 sub site without linking info: OK
Lists the WfDocumentChildAtWebLevel content type at level 4 sub site linked to the list: OK
3/ Added custom 2010 globally reusable wf to the custom root site ct

Added a custom 2010 reusable WF to WFDocument in the root site, by default the custom WF definition is not pushed to the child ct’s and does not show up in the UI not in SPD
Scanner output:

Lists the Custom 2010 reusable WF at root level without linking info: OK
4/ Add OOB 2010 approval to OOB document CT

Updating the OOB Document CT with a an OOB approval CT  CT is pushed down to all inheriting CT’s on all sub sites
Scanner output:

Lists the OOB approval WF on Document CT and all child CT’s across all sub sites: OK
5/ Add custom 2010 globally reusable wf to OOB document CT

Updating the OOB document CT with a custom 2010 globally reusable WF  CT is pushed to the child CT’s in the root site, not to the sub sites. This behavior is confirmed with SPD and SPO UI
Scanner output:

List the added custom 2010 globally reusable WF on the document CT and children in the root site: OK

**Comment by jansenbe** [comment] 2021-02-11 18:49
Closing this one as the modernization scanner is logging workflows added on a content type at content type level and not at each list that possibly can use that content type.

**Closed by jansenbe** 2021-02-11 18:49 UTC
Labels: ModernizationScanner, question
