### ISSUE TITLE
[BUG] No Workflows Reported for site with known workflows

### ISSUE THREAD

**Issue by SVG4365** [pnp/sp-dev-modernization#543] opened 2020-10-22 14:42 UTC
#### Problem Area

[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ x] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Start a Classic workflow usage (detailed) scan for a single site. Find the site's workflows in the scan report.

#### Observed Behavior

The scan runs as expected, the, but the output csv's are  empty.

#### Steps to Reproduce

Run a scan for a first site. The output is as expected.
Run a scan for a second (troublesome) site. The output file ModernizationWorkflowScanResults.csv empty. We know for a fact the site has workflows. Interesting detail: the site has spaces in it's url, replaced with %20

No error
Version 2.18

**Comment by jansenbe** [comment] 2020-10-23 16:14
Thanks for reporting this @SVG4365 .

Can you share a screenshot from SharePoint Designer showing a missing workflow?

**Comment by SVG4365** [comment] 2020-10-26 13:12
Hello @jansenbe 
I have been digging further into this. 
I found all workflows on the site (all publishing approval 2010) are associated with (InfoPath) forms in Forms libraries. 
I reproduced this on another site with the same result: no entries in the Modernization Scanner report.
![Workflows-SPD](https://user-images.githubusercontent.com/57793572/97176374-2435be80-1795-11eb-8686-df4c16733619.png)

**Comment by vgurusa** [comment] 2020-10-27 15:45
@SVG4365, have you confirmed the modernization scanner Azure AD app has Sites.FullControl.All permissions? The workflow inventory does need the Sites.FullControl.All permissions.

**Comment by SVG4365** [comment] 2020-11-02 06:28
@vgurusa indeed, that's how we have set this up.
![app-permissions](https://user-images.githubusercontent.com/57793572/97836268-36a38100-1cdc-11eb-9c28-51d37c487b9c.png)

It seems to work fine for other workflows. We are very concerned however that the scan does not return all workflows (like the ones associated with InfoPath forms) and we are missing important data for the upcoming classic workflow retirement. Any help from your side would be greatly appreciated.

Thank you
Stefaan

**Comment by mhendric** [comment] 2020-11-03 20:10
Hi @jansenbe and @vgurusa , checking if you have any updates on this investigation, and if you need any more information to proceed? Thanks.

**Comment by mhendric** [comment] 2020-11-20 16:23
Hi @jansenbe , checking again to see if there's anything you need to help out with this investigation? Given @SVG4365 's latest comments, it sounds like this issue is scoped to workflows associated with InfoPath forms, and should be reproducible.

**Comment by jansenbe** [comment] 2021-02-03 15:35
@mhendric / @vgurusa : I've been testing various WF scenarios with the latest scanner but for now I'm not able to reproduce. See below for the used test scenario. Do you have repro steps that result in a used WF which is not reported by the scanner?

1/ Inherited custom content type
-	Add new site CT (=WFDocument) inheriting from document CT
-	Add new site CT (=WFDocumentChild) inheriting from WFDocument
-	Created a sub site structure of 3 levels 
-	Added a document library on a level 3 sub site
-	Added the WFDcoument content type to a document library at level 2
-	Added the WFDocumentChild content type to the document library at level 3
-	Updated the WFDocument in the root site by adding  an OOB 2010 approval WF to it

Scanner output:
-	lists the WFDocumentChild content type in the level 3 sub site linked to the list: OK
-	lists the WFDocument content type in the level 2 sub site linked to the list: OK
-	list the WFDocument and WFDocumentChild content types in the root site without linking info: OK

2/ Use SPD to create a custom content type at sub site level
-	Add new CT (=WfDocumentChildAtWebLevel) via SPD in the level 3 sub site
-	Add new level 4 sub site 
-	Connect WfDocumentChildAtWebLevel to new doc lib at level 4 sub site

Scanner output:
-	Lists the WfDocumentChildAtWebLevel content type at level 3 sub site without linking info: OK
-	Lists the WfDocumentChildAtWebLevel content type at level 4 sub site linked to the list: OK

3/ Added custom 2010 globally reusable wf to the custom root site ct
-	Added a custom 2010 reusable WF to WFDocument in the root site, by default the custom WF definition is not pushed to the child ct’s and does not show up in the UI not in SPD

Scanner output:
-	Lists the Custom 2010 reusable WF at root level without linking info: OK

4/ Add OOB 2010 approval to OOB document CT 
-	Updating the OOB Document CT with a an OOB approval CT  CT is pushed down to all inheriting CT’s on all sub sites

Scanner output:
-	Lists the OOB approval WF on Document CT and all child CT’s across all sub sites: OK

5/ Add custom 2010 globally reusable wf to OOB document CT
-	Updating the OOB document CT with a custom 2010 globally reusable WF  CT is pushed to the child CT’s in the root site, not to the sub sites. This behavior is confirmed with SPD and SPO UI

Scanner output:
-	List the added custom 2010 globally reusable WF on the document CT and children in the root site: OK

**Comment by jansenbe** [comment] 2021-02-11 18:50
Closing this one as the modernization scanner is logging workflows added on a content type at content type level and not at each list that possibly can use that content type.

**Closed by jansenbe** 2021-02-11 18:50 UTC
Labels: ModernizationScanner, Pending feedback, question
