### ISSUE TITLE
Unable to switch to Powerapps form in Tasks list- After Site Upgraded to Modern

### ISSUE THREAD

**Issue by InfosysAdmin** [pnp/sp-dev-modernization#458] opened 2020-03-31 05:18 UTC
#### Category

[*] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[* ] Modernization Scanner: something went wrong...

After Upgrading a site to Modern, When a new Tasks list is created,unable to switch the form to Powerapps form using form settings.

![image](https://user-images.githubusercontent.com/57442089/77989681-027a7300-733d-11ea-9261-d493b8860a99.png)

**Comment by jansenbe** [comment] 2020-04-02 06:04
Hey @InfosysAdmin ,

A task list is classic by design, it will not show a modern UI as Microsoft has not built a modernized the task list and web part (we do have planner for modern task management). Given the UI is forced to classic there's no option to use PowerApps as that only works for lists showing in modern. 

This is not an issue in page transformation, so will close it but hope the answer I gave will clarify things for you.

**Closed by jansenbe** 2020-04-02 06:04 UTC
Labels: question

**Comment by ArturGentner** [comment] 2020-04-08 14:06
The problem is not only on migrated sites. We have sites that are in Classic Experiences, but in the new task lists it is no longer possible to use SharePoint Integrated PowerApps forms or even standard SharePoint forms. The cause is other. 
In the Modern Experience view the SharePoint integration should be available.
https://powerusers.microsoft.com/t5/Building-Power-Apps/Customize-Sharepoint-Online-Form-Parent-Child-Lookup-field/td-p/245171
