### ISSUE TITLE
[BUG] : ModernizationScanner never finishes scanning large amounts of sites in the tenant and writes NO logfiles

### ISSUE THREAD

**Issue by amarnath2510** [pnp/sp-dev-modernization#505] opened 2020-07-21 02:46 UTC
SharePoint Modernization Scanner Version 2.12.0.0 configured to run with Azure ACS App only  never finishes scanning large amounts of sites on a tenant (>10'000 Sites) and even worse, as the log file is written only at the end after running for several hours NO log files are available...
 Full scan never completes 
 Scan was to find only SharePoint designer workflows

After running several hours (once approx 7 or 8 hours and once over 18 hours, first try with 10 threads, second try with 30 threads) it reached once 95% and then looped endless with the message "Retrieving a batch of up to 500 search results"
 As the log file is unfortunately ONLY written when it ends successfully NO logfiles are available...

We have run the site collection with batch wise (3000 sites per batch) , still we get the same error.
Please let us know is there any away to generate the report.
![image](https://user-images.githubusercontent.com/68575809/88006929-597aa280-cafc-11ea-8214-0eac2bd581f4.png)

**Comment by jansenbe** [comment] 2020-07-22 07:10
Hi @amarnath2510 ,

Would it be possible to do a Fiddler trace when the scan get's stuck in the "retrieve a batch of up to 500 search results" loop. This will help understand whether the requests are throttled or not. There's an open issue (#498) for updating the scanner to continuously persist the results

**Comment by jansenbe** [comment] 2020-07-22 16:57
Issue #498 has been implemented, the scanner now will write the scan results to CSV files each minute.

**Comment by Chipzter** [comment] 2020-07-23 14:04
Hi Bert,
We are facing the exact same issue when scanning a mere 860 sites on one of our vanity domains, also using App ID auth. I downloaded the new release this morning, and the logs are getting written to disk periodically, but after it gets stuck in that batch retrieval loop, it seems that the output files are rewritten or touched, but there are no _new_ rows added. I'm rerunning it with fiddler now so perhaps I will be able to provide more information tomorrow unless someone else beats me to it.

  // Robert

**Comment by Chipzter** [comment] 2020-07-23 15:12
Ooo 😎 ! Here's a clue: The "IndexDocId > xxx" condition in the search query seems to not work when it needs to page result sets larger than 500 items. It keeps getting the same 500 items over and over. The IndexDocId of the last item is the same every time.
![image](https://user-images.githubusercontent.com/9699919/88303704-9f578680-cd07-11ea-8b19-ab184fb5f086.png)

**Comment by jansenbe** [comment] 2020-07-23 16:40
Hi @Chipzter ,

Been a while since we spoke :-) 

Thanks for the debugging, I'm going to try and repro this at my side

**Comment by jansenbe** [comment] 2020-07-24 06:57
Hi @Chipzter , @amarnath2510 ,

I'm prepping version 2.15 with a fix for this, if you want to test that version before I release it then please let me know.

**Comment by Chipzter** [comment] 2020-07-24 07:31
Thanks @jansenbe!
Absolutely! 🙂 Just let me know when it's available, and I can give it a go right away.

**Comment by jansenbe** [comment] 2020-07-24 07:33
It's in the place where we shared the trace file

**Comment by Chipzter** [comment] 2020-07-24 10:27
I noticed that SharePoint added QueryModifications to the search queries resulting in too many results. Explicitly setting the SourceID for the "Local SharePoint Results" result source seems to fix the issue. Additionally, unless this property is set EVERY time the query is executed, the problem reappears. Have a look at the PR and see if it makes sense.
See also: https://www.eliostruyf.com/best-practice-local-sharepoint-results-source-id-gain-search-control/
Before:
![image](https://user-images.githubusercontent.com/9699919/88382328-88b53c00-cda8-11ea-818b-ad770c9a25de.png)
After:
![image](https://user-images.githubusercontent.com/9699919/88382573-02e5c080-cda9-11ea-9b64-bbfd47b8811c.png)

**Comment by Chipzter** [comment] 2020-07-27 07:21
Hi,
Just a quick note to let you know that version 2.15 fixed this issue for me. I successfully scanned over 23,000 sites in about 22 hours with no need to break out of any infinity loop. 
Hopefully @amarnath2510's problem had the same root cause.
Thanks!

**Comment by amarnath2510** [comment] 2020-07-27 07:31
Hi Robert,

Good Day!

I have started running the scanner for 21000 sites today. I will update once it is completed. Now output is generated for every one minute.

Thanks in Advance.


Regards,
Amarnath Reddy C
CS SharePoint Applications Support
Information Systems & Technology
Rio Tinto

T: +91 9900124945
amarnath.reddy@riotinto.com<mailto:amarnath.reddy@riotinto.com>
www.riotinto.com<http://www.riotinto.com/>

**Comment by jansenbe** [comment] 2020-08-08 07:37
Closing this issue now, version 2.15 will not hang anymore due to a search query. Delays due to throttling can still happen though

**Closed by jansenbe** 2020-08-08 07:37 UTC
Labels: ModernizationScanner, question
