### ISSUE TITLE
Could not migrate the PublishingPageImage to Header in Modern page through ConvertTo-PnPClientSidePage whereas we could migrate the field to page content section as a webpart without the image getting copied to target site.

### ISSUE THREAD

**Issue by Manasa-189** [pnp/sp-dev-modernization#449] opened 2020-03-09 12:50 UTC
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[ *] Bug
[ ] Enhancement

#### Problem Area

[* ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

Could not migrate the PublishingPageImage to Header in Modern page through ConvertTo-PnPClientSidePage whereas we could migrate the field to page content section as a webpart without the image getting copied to target site.

Note:  The image in field PublishingPageImage in classic page is referenced from another site collection under same tenant.

#### Expected or Desired Behavior

The PublishingPageImage should get copied to the target site site assets and display in the header of the modern page

#### Observed Behavior

No Header image is present in the migrated page nor the image got copied to target site

#### Steps to Reproduce

1) Exported the custom page layout mapping file using Export-PnPClientSidePageMapping
2) Updated the Header section of the respective page layout with 

<Field Name="PublishingPageImage" HeaderProperty="ImageServerRelativeUrl" Functions="ToImageUrl({PublishingPageImage})" />

#### Submission Guidelines

_Delete this section after reading_

- All suggestions or bugs are welcome, please let us know what's on your mind.
- If you checked the **"Page Transformation: Error during the setup/use of the Page Transformation UI solution"** checkbox then please provide:
  - The output of the following 2 PnP PowerShell statements: `Get-PnPStorageEntity` and `Get-PnPTenantServicePrincipalPermissionGrants`
  - The errors listed inside the browser's developer tools window (F12), if possible tested with Chrome as browser
  - The versions of the **sharepointpnp-pagetransformation-client-solution** and **sharepointpnp-pagetransformation-central-solution** solutions in your SharePoint tenant app catalog
- If you checked the **"Page Transformation: Error during the use of page transformation from PnP PowerShell"** checkbox then please provide:
  - The output you see in your PowerShell session
  - The output generated by calling `Get-PnPException`
  - The PnP PowerShell version. Run `get-module -Name SharePointPnPPowerShellOnline` and copy the version info
- If you checked the **"Page Transformation: Error during the use of page transformation from .Net"** checkbox then please provide:
  - The exact error message you get
  - The stack trace of the error
  - The version of the **SharePointPnP.Modernization.Framework.dll** assembly

Thanks for your contribution! Sharing is caring.

**Comment by pkbullock** [comment] 2020-03-09 13:10
@Manasa-189 thank you for raising the issue, please can you provide any logs, please see the example script for producing this lines, 127-140 in the script: https://github.com/SharePoint/sp-dev-modernization/blob/master/Scripts/PageTransformation/Convert-PublishingPages.ps1 

Also please include the repo steps and sample URLs.

**Comment by jansenbe** [comment] 2020-03-09 17:01
@Manasa-189: Also please share the page layout mapping file you're testing with

**Comment by Manasa-189** [comment] 2020-03-10 10:18
[ArticleWithHero.txt](https://github.com/SharePoint/sp-dev-modernization/files/4311702/ArticleWithHero.txt)

ArticleWithHero -custom page layout

**Comment by jansenbe** [comment] 2020-03-10 12:30
@Manasa-189 : did cross check things in the code and assets living outside of the site collection hosting the page to be modernized are **not** copied over. Depending on what works best for you it's recommended to either update the source page to point to an asset in the site collection before running transformation or alternatively manually fix the created page after transformation. Given a site collection is often seen as security boundary most publishing portals have the needed assets in the same site collection. When you have multiple webs then the asset can live in another web of the site collection (e.g. common is to have assets in the root web being referenced by pages in child webs).

**Comment by jansenbe** [comment] 2020-03-24 10:48
Closing as the seen behavior is by design

**Closed by jansenbe** 2020-03-24 10:48 UTC
Labels: PageTransformationEngine, Pending feedback, question
